### ISSUE TITLE
Support for large scale screening

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#15]
Say if I'm interested in parameterising a large number of related small molecules.

If I do a batch of hessian calculations for all of the molecules on the cluster, then I would like to do another batch of dihedral scans of all the molecules. In the current setup, the dihedral that is shared between molecules will be scanned more than once.

Is it possible that qforce will check if the corresponding file has been generated in '~/qforce_fragments' and give an option to skip the corresponding dihedral?

Or some functions could exist that go through the folders and remove the redundant dihedrals.

**Comment by selimsami** [comment]
>If I do a batch of hessian calculations for all of the molecules on the cluster, then I would like to do another batch of dihedral scans of all the molecules. In the current setup, the dihedral that is shared between molecules will be scanned more than once.

Since the equivalent dihedrals will have the exact same input file name, you could implement in your batch submission pipeline a few lines to remember the dihedrals you have already submitted and skip if you encounter again.

> Is it possible that qforce will check if the corresponding file has been generated in '~/qforce_fragments' and give an option to skip the corresponding dihedral?

If QM results are in qforce_fragments, it will automatically use them if you encounter the same dihedral. But your problem is that they are not.

One could easily add a new setting, f.e. "batch_run = True", that skips generating an input for the dihedral even if the QM result is missing (so if the fragment has been encountered before but does not have QM results yet)

> Or some functions could exist that go through the folders and remove the redundant dihedrals.

This option I like less. It sounds like something that you can add to your batch submission pipeline rather than qforce.
